name: Dependabot Auto-merge

on:
  pull_request_target:
    types: [labeled, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for patch and minor updates
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: |
          echo "Auto-merging ${{ steps.metadata.outputs.update-type }} update (no tests to wait for)"
          gh pr merge --merge "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log major version updates (manual review required)
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: |
          echo "Major version update detected for ${{ steps.metadata.outputs.dependency-names }}. Manual review required."
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"